[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
decorations = "Full"                       # Transparent, Full
dimensions = { columns = 130, lines = 38 }
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
# TIP: Hack Nerd Font have bigger icons, then Hack Nerd Font Mono
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 18

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[keyboard]
bindings = [
  # Special mappings for alacritty + tmux + vim
  #
  # Helper list of rerest unicode chars https://graphicdesign.stackexchange.com/a/16492/102081
  { chars = "\u2042", key = "F2", mods = "Shift" }, # special meaning for Shift+F2 = \u2042 = ⁂
]
