---
singleQuote: true
tabWidth: 4
bracketSpacing: true
arrowParens: avoid
semi: true
printWidth: 120
htmlWhitespaceSensitivity: strict
bracketSameLine: true
trailingComma: none
overrides:
  - files:
      # by default package.json have 2 spaces
      - "package.json"
    options:
      tabWidth: 2
