tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts" # Nerd Fonts

# Basic
brew "coreutils"
brew "bash"
brew "curl"
brew "wget"
brew "gawk"
brew "imagemagick"
brew "jq"
brew "git"
brew "nmap"
brew "tree"
brew "pandoc"
brew "k9s"
brew "helm"
brew "kubectx"
brew "kubernetes-cli", link: false
brew "awscli"
brew "minikube"
brew "shellcheck"
brew "svgo"
brew "jsonlint"
brew "go"
brew "golang-migrate" # go migrations
brew "editorconfig"
brew "neovim"
brew "vim"
brew "fd" # nvim telescope
brew "wrk" # measure http sever speed (req/res)
brew "stylua" # lua formatter
brew "git-delta" # helps with better visual diff the content
brew "mutt" # console email client
brew "awk" # for advance search & test manupulation
brew "rustfmt"

# GPG - to signed your commits
brew "gnutls"
brew "pinentry"
brew "pinentry-mac"
brew "gnupg"

# Support
brew "lua"
brew "luajit"
brew "luarocks"
brew "python@3.9"
brew "rbenv" # Ruby version manager
brew "pyenv" # Python version manager

# Usibility
brew "podman"

# Productivity
cask "amethyst"
cask "font-hack"
brew "watch"
cask "lens"
brew "fzf"
brew "cscope"
brew "macvim" # MacVim (not the terminal version)
brew "ripgrep"
brew "ansible" # managing multiple servers
cask "caffeine" # prevent system from going to sleep
brew "ollama"
brew "audacity"

# Browsers
cask "google-chrome"
cask "brave-browser"
cask "firefox"

# Linters & parsers
brew "luacheck"
brew "prettier"

# Tmux
brew "tmux"
brew "reattach-to-user-namespace" # for copy from tmux to mac namespace

# Others
brew "cmake"
brew "gobject-introspection"
brew "harfbuzz"
brew "libheif"
brew "unbound"
brew "guile"
brew "librsvg"
brew "pango"
brew "nghttp2"

# Networking
cask "wireshark" # UI app

# vi: ft=ruby
